### ISSUE TITLE
Multi Operating System Support

### ISSUE THREAD

**Issue by sudo-rsingh** [GreatRSingh/GoDoList#9]
Remove the binary file and add instructions of creating it.

People use different operating systems and we should support all.

**Comment by sudo-rsingh** [comment]
@Meru45 Complete this as a priority
- [ ] Tutorial to make the binary. [Add that to the readme.md file]
- [ ] Remove that binary file or add it to git ignore.

**Comment by Meru45** [comment]
Issue resolved...

**Comment by sudo-rsingh** [comment]
> Issue resolved...

Thanks @Meru45
